name: Sync Fork and Build Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Ce workflow s'exécute chaque jour à minuit UTC
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git configuration
      run: |
        git config --global user.email "laster13012@gmail.com"
        git config --global user.name "laster13"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/philamp/jellygrail.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main --allow-unrelated-histories

    - name: Ensure .gitattributes is set
      run: |
        echo "Dockerfile merge=ours" > .gitattributes
        git add .gitattributes
        git commit -m "Ensure .gitattributes to protect Dockerfile from merges" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin main # Assurez-vous que la branche est correcte

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: docker/
        push: true
        tags: ghcr.io/laster13/jellygrail:latest # Remplacez par votre nom d'utilisateur GitHub et le nom de l'image
