name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every day at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Git configuration
      run: |
        git config --global user.email "laster13012@gmail.com"
        git config --global user.name "laster13"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/philamp/jellygrail.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main --allow-unrelated-histories

    - name: Push changes
      run: |
        git push origin main
