name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every day at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: 'votre_nom_utilisateur/votre_fork' # Remplacez par votre nom d'utilisateur GitHub et le nom de votre fork
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream remote
      run: git remote add upstream https://github.com/nom_utilisateur/original_repo.git # Remplacez par l'URL du dépôt original

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main # Assurez-vous que la branche est correcte

    - name: Push changes
      run: |
        git push origin main # Assurez-vous que la branche est correcte
